name: Run tests
on: [push, pull_request]

jobs:
  Run-Tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install neovim
        run: |
          curl -fsSL https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-linux64.tar.gz | tar -zxf - nvim-linux64/bin/nvim
          mv nvim-linux64/bin/nvim /usr/local/bin/
          nvim --version

      - name: Run tests
        run: ./tests.lua
